### ISSUE TITLE
Publishing release date on the package webpage 

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GitHubPagesForGAP#11]
In addition to the version, it may be useful to extract from PackageInfo.g the release date as well.

**Comment by fingolfin** [comment]
The release date always gets extracted, this has been the case since the very first version of GitHubPagesForGAP. It is, however, not shown by the default `index.md`.

I assume what you are really asking for is to change the default `index.md` to show the release date in a sensible spot. Well, PRs are welcome... :-)

**Comment by fingolfin** [comment]
Ah well, never mind, I just implemented this in a51f031a1ed5b3451f8e1915dd8c2fc863c1ed33

**Comment by olexandr-konovalov** [comment]
@fingolfin 
> I assume what you are really asking for is to change the default index.md to show the release date in a sensible spot

thanks, you read my mind :) 

That was in the title of the PR (Publishing release date on the package webpage) but perhaps when one reads the comment, it is wise to replicate the title as well.
