### ISSUE TITLE
Which packages use GitHubPagesForGAP?

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GitHubPagesForGAP#12]
The README says -
```
## Packages using GitHubPagesForGAP
Packages using GitHubPagesForGAP include the following:
...
```
which is outdated. Perhaps replace by more generic "is used by more than XX packages, many of which are listed at https://gap-packages.github.io/, for example packages K, L, M, and N" ?

**Comment by fingolfin** [comment]
I don't see what is outdated about that list. The text clearly says: "include the following", which does not contradict the fact that there are now many more. The list is primarily there so that people can get an idea how such a package homepage looks, hence the concrete lists. In contrast, pointing to https://gap-packages.github.io/ is less useful, as not every package there uses GitHubPagesForGAP (and not all are using the most recent versions, etc.)

**Comment by olexandr-konovalov** [comment]
@fingolfin: outdated = incomplete. It's your choice which packages to mention there as examples. My point actually was that if we advise other package authors to use their tool, then it will help to show that this is by now used by MANY packages (what is in fact the case).
